type Promotion {
  id: String,
  title:String,
  description: String,
  currentSalary: Float,
  newSalary: Float,
  allowedBy: String,
  createdAt: String,
  updatedAt: String,
  deleted: Boolean,
  deletedAt: String,
  employeeId: String
}

input HrPromotionInput {
  title:String,
  description: String,
  currentSalary: String,
  newSalary: String,
  allowedBy: String,
  employeeId: String
}

type HrPromotionUniqueResponse {
	status: Int,
	data: Promotion,
	messages: [String],
	isValid: Boolean
}

type Mutation {
  createHrPromotion(data: HrPromotionInput!): HrPromotionUniqueResponse
  deleteHrPromotion(id: String!): HrPromotionUniqueResponse
}
